baseUrl = "https://kevinwalkup.com"
languageCode = "en-us"
title = "Kevin Walkup"
theme = "ananke"

enableRobotsTXT = true
Paginate = 6
DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  twitter = "https://twitter.com/WalkupKevin"
  linkedin = "https://www.linkedin.com/in/kevinwalkup/"
  background_color_class = "bg-near-black"
  featured_image = "/images/hero-image.jpg"
  recent_posts_number = 3
